version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
    - .:/NDS_Choises

    ports:
    - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'nds_choises'
      POSGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '250768ak'
    restart: always

